const CONTENT_TYPE = 'TODOS';

export const CREATE_NEW_TODO_REQUESTED = `${CONTENT_TYPE}_CREATE_NEW_TODO_REQUESTED`;
export const DELETE_TODO_REQUESTED = `${CONTENT_TYPE}_DELETE_TODO_REQUESTED`;
export const DONE_TODO_REQUESTED = `${CONTENT_TYPE}_DONE_TODO_REQUESTED`;
